version: 2

updates:
  # Gradle (Android dependencies)
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
