package io.okaiwa.features.auth.domain.entities

/**
 * Phone country metadata — ISO code, display name, dial code, flag emoji.
 *
 * The flag emoji is derived from the ISO-3166-1 alpha-2 code via the
 * standard regional indicator symbol trick, keeping the catalog free
 * of image assets.
 */
data class Country(
    val isoCode: String,
    val name: String,
    val dialCode: String,
) {
    val flagEmoji: String
        get() = isoCode.uppercase().map { char ->
            // Regional Indicator Symbols live at U+1F1E6..U+1F1FF, offset
            // from the latin uppercase 'A' by 0x1F1A5.
            Character.toChars(0x1F1A5 + char.code)
        }.flatMap { it.toList() }.joinToString("")
}

/**
 * Static catalog of countries for the phone number picker.
 * Ordered alphabetically by display name for the default list view.
 * The picker UI lets the user search by name or dial code.
 */
object Countries {
    val all: List<Country> = listOf(
        Country("AF", "Afghanistan", "+93"),
        Country("AL", "Albanie", "+355"),
        Country("DZ", "Algérie", "+213"),
        Country("DE", "Allemagne", "+49"),
        Country("AD", "Andorre", "+376"),
        Country("AO", "Angola", "+244"),
        Country("AR", "Argentine", "+54"),
        Country("AM", "Arménie", "+374"),
        Country("AU", "Australie", "+61"),
        Country("AT", "Autriche", "+43"),
        Country("AZ", "Azerbaïdjan", "+994"),
        Country("BH", "Bahreïn", "+973"),
        Country("BD", "Bangladesh", "+880"),
        Country("BE", "Belgique", "+32"),
        Country("BJ", "Bénin", "+229"),
        Country("BY", "Biélorussie", "+375"),
        Country("BO", "Bolivie", "+591"),
        Country("BA", "Bosnie-Herzégovine", "+387"),
        Country("BR", "Brésil", "+55"),
        Country("BG", "Bulgarie", "+359"),
        Country("BF", "Burkina Faso", "+226"),
        Country("KH", "Cambodge", "+855"),
        Country("CM", "Cameroun", "+237"),
        Country("CA", "Canada", "+1"),
        Country("CL", "Chili", "+56"),
        Country("CN", "Chine", "+86"),
        Country("CY", "Chypre", "+357"),
        Country("CO", "Colombie", "+57"),
        Country("CG", "Congo", "+242"),
        Country("CD", "Congo (RDC)", "+243"),
        Country("KR", "Corée du Sud", "+82"),
        Country("CI", "Côte d'Ivoire", "+225"),
        Country("HR", "Croatie", "+385"),
        Country("CU", "Cuba", "+53"),
        Country("DK", "Danemark", "+45"),
        Country("EG", "Égypte", "+20"),
        Country("AE", "Émirats arabes unis", "+971"),
        Country("EC", "Équateur", "+593"),
        Country("ES", "Espagne", "+34"),
        Country("EE", "Estonie", "+372"),
        Country("US", "États-Unis", "+1"),
        Country("ET", "Éthiopie", "+251"),
        Country("FI", "Finlande", "+358"),
        Country("FR", "France", "+33"),
        Country("GA", "Gabon", "+241"),
        Country("GE", "Géorgie", "+995"),
        Country("GH", "Ghana", "+233"),
        Country("GR", "Grèce", "+30"),
        Country("GT", "Guatemala", "+502"),
        Country("GN", "Guinée", "+224"),
        Country("HT", "Haïti", "+509"),
        Country("HN", "Honduras", "+504"),
        Country("HK", "Hong Kong", "+852"),
        Country("HU", "Hongrie", "+36"),
        Country("IN", "Inde", "+91"),
        Country("ID", "Indonésie", "+62"),
        Country("IQ", "Iraq", "+964"),
        Country("IR", "Iran", "+98"),
        Country("IE", "Irlande", "+353"),
        Country("IS", "Islande", "+354"),
        Country("IL", "Israël", "+972"),
        Country("IT", "Italie", "+39"),
        Country("JM", "Jamaïque", "+1"),
        Country("JP", "Japon", "+81"),
        Country("JO", "Jordanie", "+962"),
        Country("KZ", "Kazakhstan", "+7"),
        Country("KE", "Kenya", "+254"),
        Country("KW", "Koweït", "+965"),
        Country("LA", "Laos", "+856"),
        Country("LV", "Lettonie", "+371"),
        Country("LB", "Liban", "+961"),
        Country("LY", "Libye", "+218"),
        Country("LT", "Lituanie", "+370"),
        Country("LU", "Luxembourg", "+352"),
        Country("MK", "Macédoine du Nord", "+389"),
        Country("MG", "Madagascar", "+261"),
        Country("MY", "Malaisie", "+60"),
        Country("ML", "Mali", "+223"),
        Country("MT", "Malte", "+356"),
        Country("MA", "Maroc", "+212"),
        Country("MU", "Maurice", "+230"),
        Country("MR", "Mauritanie", "+222"),
        Country("MX", "Mexique", "+52"),
        Country("MD", "Moldavie", "+373"),
        Country("MC", "Monaco", "+377"),
        Country("MN", "Mongolie", "+976"),
        Country("ME", "Monténégro", "+382"),
        Country("MZ", "Mozambique", "+258"),
        Country("NA", "Namibie", "+264"),
        Country("NP", "Népal", "+977"),
        Country("NI", "Nicaragua", "+505"),
        Country("NE", "Niger", "+227"),
        Country("NG", "Nigeria", "+234"),
        Country("NO", "Norvège", "+47"),
        Country("NZ", "Nouvelle-Zélande", "+64"),
        Country("OM", "Oman", "+968"),
        Country("UG", "Ouganda", "+256"),
        Country("UZ", "Ouzbékistan", "+998"),
        Country("PK", "Pakistan", "+92"),
        Country("PA", "Panama", "+507"),
        Country("PY", "Paraguay", "+595"),
        Country("NL", "Pays-Bas", "+31"),
        Country("PE", "Pérou", "+51"),
        Country("PH", "Philippines", "+63"),
        Country("PL", "Pologne", "+48"),
        Country("PT", "Portugal", "+351"),
        Country("QA", "Qatar", "+974"),
        Country("RO", "Roumanie", "+40"),
        Country("GB", "Royaume-Uni", "+44"),
        Country("RU", "Russie", "+7"),
        Country("RW", "Rwanda", "+250"),
        Country("SV", "Salvador", "+503"),
        Country("SA", "Arabie saoudite", "+966"),
        Country("SN", "Sénégal", "+221"),
        Country("RS", "Serbie", "+381"),
        Country("SG", "Singapour", "+65"),
        Country("SK", "Slovaquie", "+421"),
        Country("SI", "Slovénie", "+386"),
        Country("SO", "Somalie", "+252"),
        Country("SD", "Soudan", "+249"),
        Country("LK", "Sri Lanka", "+94"),
        Country("SE", "Suède", "+46"),
        Country("CH", "Suisse", "+41"),
        Country("SR", "Suriname", "+597"),
        Country("SY", "Syrie", "+963"),
        Country("TJ", "Tadjikistan", "+992"),
        Country("TW", "Taïwan", "+886"),
        Country("TZ", "Tanzanie", "+255"),
        Country("TD", "Tchad", "+235"),
        Country("CZ", "Tchéquie", "+420"),
        Country("TH", "Thaïlande", "+66"),
        Country("TG", "Togo", "+228"),
        Country("TN", "Tunisie", "+216"),
        Country("TM", "Turkménistan", "+993"),
        Country("TR", "Turquie", "+90"),
        Country("UA", "Ukraine", "+380"),
        Country("UY", "Uruguay", "+598"),
        Country("VE", "Venezuela", "+58"),
        Country("VN", "Viêt Nam", "+84"),
        Country("YE", "Yémen", "+967"),
        Country("ZM", "Zambie", "+260"),
        Country("ZW", "Zimbabwe", "+263"),
    ).sortedBy { it.name }

    /** Best-effort default — matches the device region when available. */
    fun findByIso(iso: String): Country? = all.firstOrNull { it.isoCode.equals(iso, ignoreCase = true) }

    /** Default fallback used when the device locale is unknown. */
    val default: Country = findByIso("FR") ?: all.first()
}
